
apiVersion: apps/v1  
kind: Deployment  
metadata:
  name: db-deployment 
spec:
  selector:
    matchLabels:
      app: sparta-db  
  replicas: 1
  template:
    metadata:
      labels:
        app: sparta-db
    spec:
      containers:
      - name: sparta-db
        image: bitnami/mongodb:7.0.6 
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: mongodb-storage
            mountPath: /bitnami/mongodb
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc
